### ISSUE TITLE
Add Semaphore on event unsubscribe

### ISSUE THREAD

**Issue by NIKL45** [theelims/ESP32-sveltekit#64]
First of all: I edited the project quite a bit. So the following issue might not apply, but I think it could still improve your code.

I am running the [AnalyticsService.h](https://github.com/theelims/ESP32-sveltekit/blob/main/lib/framework/AnalyticsService.h) as is (runs a separate Task). 
But the frontend is modified, so that the client is only subscribed to the "analytics" event, when the "System Metrics" or "System Status" page is displayed. 
For this is removed the subscribe (and unsubscribe) to this even from here: https://github.com/theelims/ESP32-sveltekit/blob/86e165f1d4d552d195c5670c8f67519e15aa378c/interface/src/routes/%2Blayout.svelte#L48
And added a `socket.on('analytics', ...)` onMount in SystemMetrics.svelte and SystemStatus.svelte (also `socket.off(...)` onDestroy).

With this the client sends an EventSocket request: `{"event":"unsubscribe","data":"analytics"}` when the client leaves the SystemMetrics or SystemStatus page.
If the client switches pages multiple times and leaves the page SystemMetrics for the third time, my ESP32C3-DevKitM-1 crashes, giving me the following **`Load access fault`**:

```15:01:37.408 > [ 34809][V][EventSocket.cpp:63] onFrame(): [EventSocket] ws[10.0.0.2][52] request: {"event":"unsubscribe","data":"analytics"}
15:01:37.434 > [ 34820][V][EventSocket.cpp:88] onFrame(): [EventSocket] Unsubscribed from event: unsubscribe
15:01:38.611 > ata":{"uptime":34,"free_heap":177396,"total_heap":288164,"min_free_heap":160796,"max_alloc_heap":151540,"fs_used":0,"fs_total":0,"core_temp":49.2}}
15:01:38.611 > Guru Meditation Error: Core  0 panic'ed (Load access fault). Exception was unhandled.
15:01:38.682 > 
15:01:38.682 > Core  0 register dump:
15:01:38.682 > MEPC    : 0x42014682  RA      : 0x42014730  SP      : 0x3fcb3b80  GP      : 0x3fc8d800  
15:01:38.695 > TP      : 0x3fc617e4  T0      : 0x00000009  T1      : 0x40387f0c  T2      : 0x000000ff  
15:01:38.701 > S0/FP   : 0x3fcb5088  S1      : 0x3fcb3bbc  A0      : 0x00000000  A1      : 0x00000000  
15:01:38.706 > A2      : 0x00000000  A3      : 0x00000001  A4      : 0xae30bb9f  A5      : 0xae30bb9f  
15:01:38.712 > A6      : 0x3fcb3ac4  A7      : 0x00001388  S2      : 0x000000aa  S3      : 0x3fcb3cac  
15:01:38.712 > S4      : 0x00000000  S5      : 0xffffffff  S6      : 0x3fca9604  S7      : 0x3fcb55d8  
15:01:38.734 > S8      : 0x3fca9604  S9      : 0x3c0f9000  S10     : 0x000084e5  S11     : 0x3c0f9438  
15:01:38.739 > T3      : 0x00000000  T4      : 0x000000ff  T5      : 0x0000000a  T6      : 0x0000002e  
15:01:38.750 > MSTATUS : 0x00001881  MTVEC   : 0x40380001  MCAUSE  : 0x00000005  MTVAL   : 0x00000008
15:01:38.750 > MHARTID : 0x00000000
15:01:38.750 >
15:01:38.750 > Stack memory:
15:01:38.761 > 3fcb3b80: 0x000000aa 0x3fcb5088 0xa5a5a5a5 0x00000009 0xa5a5a5a5 0x3fc96000 0x3fc96690 0x3fc90bb8
  #0  0x3fc96690 in ?? at lib/EventSocket/EventSocket.cpp:10

15:01:38.762 > 3fcb3ba0: 0x00000400 0x3fc97a78 0x00000034 0x3c0f9fb4 0x0200000a 0x000000aa 0x3fcb3bbc 0x3fc8d020
15:01:39.291 > 3fcb3bc0: 0x3fcb4300 0x3fcb4e64 0x00140080 0x3fcb5cc0 0x3c0f5944 0x4050567d 0x566cf41f 0x42048a4a
  #0  0x42048a4a in temperature_sensor_get_raw_value at /home/runner/work/esp32-arduino-lib-builder/esp32-arduino-lib-builder/esp-idf/components/esp_hw_support/port/esp32c3/sar_periph_ctrl.c:174

15:01:39.291 > 3fcb3be0: 0x00000000 0x3fcb3c44 0x3fcb3bc8 0x00040001 0x3fcbffff 0x00030000 0xffff5920 0x00000000
15:01:39.291 > 3fcb3c00: 0x00000000 0x00000000 0x08cb434c 0x00000000 0x00000000 0x00000000 0x090f598c 0xae30bb9f
15:01:39.291 > 3fcb3c20: 0x3fcb3ca4 0x3c0f5958 0x3c0f594c 0x00000000 0x00000000 0x00000000 0x4244cccd 0x3fc96640
  #0  0x3fc96640 in ?? at src/main.cpp:49

15:01:39.291 > 3fcb3c40: 0x3fc90bb4 0x3c0f5958 0x3c0f594c 0x3c0f595c 0x3c0f5944 0x3fc96000 0x3fcb3c6c 0x42001658
  #0  0x3fc90bb4 in ?? at src/main.cpp:45
  #1  0x42001658 in AnalyticsService::_loop() at lib/AnalyticsService/AnalyticsService.h:57 (discriminator 3)

15:01:39.291 > 3fcb3c60: 0x000083fc 0x3fcb3ca4 0x3fcb3c6c 0x3fc8d020 0xa5a5a500 0x00000000 0x00100080 0x3fcb42dc
15:01:39.291 > 3fcb3c80: 0x42001686 0x40388f76 0x00000000 0x3fc8d800 0x3fc617e4 0x00000000 0x3fcb3c78 0x00040001
  #0  0x42001686 in AnalyticsService::_loopImpl(void*) at lib/AnalyticsService/AnalyticsService.h:40
  #1  0x40388f76 in _prvTaskExitError at /home/runner/work/esp32-arduino-lib-builder/esp32-arduino-lib-builder/esp-idf/components/freertos/port/riscv/port.c:126
      (inlined by) prvTaskExitError at /home/runner/work/esp32-arduino-lib-builder/esp32-arduino-lib-builder/esp-idf/components/freertos/port/riscv/port.c:140
  #2  0x3fc8d800 in __global_pointer$ at ??:?

15:01:39.291 > 3fcb3ca0: 0x0000ffff 0x000f0000 0xffff6620 0x6c616e61 0x63697479 0x00000073 0x89000000 0xae30bb9f
15:01:39.291 > 3fcb3cc0: 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000
15:01:39.291 > 3fcb3ce0: 0x00000000 0x00000000 0x00000000 0x4200168c 0x00000000 0x00000000 0x00000000 0x40388f76
  #0  0x4200168c in _GLOBAL__sub_I_APssid at src/main.cpp:116
  #1  0x40388f76 in _prvTaskExitError at /home/runner/work/esp32-arduino-lib-builder/esp32-arduino-lib-builder/esp-idf/components/freertos/port/riscv/port.c:126
      (inlined by) prvTaskExitError at /home/runner/work/esp32-arduino-lib-builder/esp32-arduino-lib-builder/esp-idf/components/freertos/port/riscv/port.c:140

15:01:39.291 > 3fcb3d00: 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0xa5a5a5a5 0xa5a5a5a5 0xa5a5a5a5
15:01:39.291 > 3fcb3d20: 0xa5a5a5a5 0xa5a5a5a5 0xbaad5678 0x00000160 0xabba1234 0x00000154 0x3fcb3950 0x000083fc
15:01:39.291 > 3fcb3d40: 0x3fc9267c 0x3fc9267c 0x3fcb3d38 0x3fc92674 0x00000018 0xfeea1c19 0x84c775c6 0x3fcb3d38
15:01:39.291 > 3fcb3d60: 0x00000000 0x00000001 0x3fcb2540 0x6c616e41 0x63697479 0x65532073 0x00697672 0x00000000
15:01:39.291 > 3fcb3d80: 0x3fcb3d20 0x00000000 0x00000001 0x3fcb3ff8 0x420233cc 0x00000000 0x3fc97d84 0x3fc97dec
  #0  0x420233cc in pthread_local_storage_thread_deleted_callback at /home/runner/work/esp32-arduino-lib-builder/esp32-arduino-lib-builder/esp-idf/components/pthread/pthread_local_storage.c:129

15:01:39.291 > 3fcb3da0: 0x3fc97e54 0x00000000 0x00000000 0x00000001 0x00000000 0x00000000 0x00000000 0x4209cc26
  #0  0x4209cc26 in _cleanup_r at /builds/idf/crosstool-NG/.build/HOST-x86_64-w64-mingw32/riscv32-esp-elf/src/newlib/newlib/libc/stdio/findfp.c:229

15:01:39.291 > 3fcb3dc0: 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000
15:01:39.291 > 3fcb3de0: 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000
15:01:39.291 > 3fcb3e00: 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000
15:01:39.291 > 3fcb3e20: 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000
15:01:39.291 > 3fcb3e40: 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000
15:01:39.291 > 3fcb3e60: 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000
15:01:39.291 > 3fcb3e80: 0x00000000 0x00000000 0x59000000 0xbaad5678 0x000000b4 0xabba1234 0x000000a8 0x00000008
15:01:39.291 > 3fcb3ea0: 0x00000000 0x0000007b 0x00000000 0xffffffff 0xffffffff 0xffffffff 0xffffffff 0xffffffff
15:01:39.291 > 3fcb3ec0: 0xffffffff 0xffffffff 0xffffffff 0xffffffff 0xffffffff 0xffffffff 0xffffffff 0x0000003b
15:01:39.291 > 3fcb3ee0: 0x00000000 0xffffffff 0xffffffff 0xffffffff 0xffffffff 0xffffffff 0xffffffff 0xffffffff
15:01:39.291 > 3fcb3f00: 0xffffffff 0xffffffff 0xffffffff 0xffffffff 0xffffffff 0xffffffff 0xffffffff 0xffffffff
15:01:39.291 > 3fcb3f20: 0xffffffff 0xffffffff 0xffffffff 0xffffffff 0xffffffff 0x000000bd 0x00000000 0x3fc8dff8
  #0  0x3fc8dff8 in __global_pointer$ at ??:?

15:01:39.291 > 3fcb3f40: 0x00000000 0xbaad5678 0x00000024 0xabba1234 0x00000018 0x00000000 0x00000000 0x00000000
15:01:39.291 > 3fcb3f60: 0x3fcb3f58 0x3fcb3f58 0x00000000 0xbaad5678 0x0000001c 0xabba1234 0x00000010 0x0200000a
15:01:39.291 >
15:01:39.291 >
15:01:39.291 >
15:01:39.291 > ELF file SHA256: b26d640cb8a573ed
15:01:39.291 >
15:01:39.291 > Rebooting...
15:01:39.291 > ESP-ROM:esp32c3-api1-20210207
15:01:39.291 > Build:Feb  7 2021
15:01:39.291 > rst:0x3 (RTC_SW_SYS_RST),boot:0xc (SPI_FAST_FLASH_BOOT)
15:01:39.291 > Saved PC:0x403818fc
  #0  0x403818fc in esp_restart_noos_dig at /home/runner/work/esp32-arduino-lib-builder/esp32-arduino-lib-builder/esp-idf/components/esp_system/esp_system.c:53 (discriminator 1)
```

This doesn't occur when I reload the page multiple times (which also triggers a new subscribe) !

After digging into the code I found out, that a Semaphore is used in `EventSocket::onWSClose`

https://github.com/theelims/ESP32-sveltekit/blob/86e165f1d4d552d195c5670c8f67519e15aa378c/lib/framework/EventSocket.cpp#L42-L51

But NO Semaphore is used for unsubscribing:

https://github.com/theelims/ESP32-sveltekit/blob/86e165f1d4d552d195c5670c8f67519e15aa378c/lib/framework/EventSocket.cpp#L91-L95

With that knowledge I add a `xSemaphoreTake(...)` and `xSemaphoreGive(...)` around the unsubscribe:
[line 91 - EventSocket.cpp]:

```c++
else if (event == "unsubscribe")
            {
                xSemaphoreTake(clientSubscriptionsMutex, portMAX_DELAY);
                client_subscriptions[doc["data"]].remove(request->client()->socket());
                xSemaphoreGive(clientSubscriptionsMutex);
                ESP_LOGV("EventSocket", "Unsubscribed from event: %s", event);
            }
```

After that, my problem was gone.
Perhaps this could (or should) be added to your code as well.
If not, I would be interested to know why you didn't use a semaphore in your code :-)

**Comment by theelims** [comment]
Hi,

thanks for tracking down this bug. If you like you can make a pull request for that. Or I'll include it with the next release.
